title: title: <p align="center"> Amit Arora </p> 
logo: /assets/img/logo.png
description: 
<br>
I am a Data Visualization Expert and an on enroute to Journey of Data Scientist , <br>
I am pursuing my Masters in Data Science from University of Arizona 
<br>
</p>


